### ISSUE TITLE
Stream generation failed

### ISSUE THREAD

**Issue by krancan** [cwilso/PitchDetect#18]
I get Stream generation failed alert when using live input. I think, https is problem. Is it possible to use live input via http? On localhost works perfect.

**Comment by dav-m85** [comment]
Running the server with https solved the issue. I haven't found any mention of SSL being mandatory in the documentation, maybe I looked in the wrong place ? https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

**Comment by Ravenstine** [comment]
Apparently, this is a Chrome thing and not something specific to the actual spec for getUserMedia.
https://webrtchacks.com/chrome-secure-origin-https/

Overall, I think it's a good decision.  It's just a drag that any demos I have involving getUserMedia keep breaking every 8 or so months because of changes like this.

**Comment by cwilso** [comment]
@dav-m85, it is mentioned in that page - note [3].  There isn't a way to use getUserMedia in Chrome on non-secure domains.
